### ISSUE TITLE
Define menu apa saja yg akan ditampilkan di halaman utama

### ISSUE THREAD

**Issue by mazipan** [phpid-jakarta/phpid-jakarta.github.io#15]
Saat ini hanya tentang kami

**Comment by ekojs** [comment]
### Mungkin sementara ini dulu yah ?

- title: "Profil"
  href: "#"
  sub:
  - title: "Tentang Kami"
    href: "tentang_kami.html"
  - title: "Visi - Misi"
    href: "visi_misi.html"

- title: "Program Kerja"
  href: "program_kerja.html"

- title: "Galeri"
  href: "#"
  sub:
  - title: "Foto"
    href: "galeri_foto.html"
  - title: "Video"
    href: "galeri_video.html"

**Comment by ekojs** [comment]
Untuk sampai dengan saat ini menunya sbb: [List Menu](https://github.com/phpid-jakarta/phpid-jakarta.github.io/blob/master/_data/menu.yml)

- [ ] Define Menu masih open pada issue #15
- [ ] Styling Menu masih open pada issue #17 
- [ ] Konten pada setiap menu masih belum, open pada issue #14

**Comment by mazipan** [comment]
Ini saya close ya, tinggal konten saja.
